---
- hosts: all
  sudo: true
  vars:
    rvm1_rubies:
      - jruby-1.7.18
  pre_tasks:
    - name: Install dependencies
      apt: "name={{ item }} state=latest"
      with_items:
        - git
        - maven
  roles:
    - rvm
  tasks:
    - name: Ensure that the gem home is set properly
      lineinfile: dest=/home/vagrant/.bashrc state=present line='export GEM_HOME=$(ruby -e 'puts Gem.user_dir')'
